// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCRLOuKuu-8Hu4Yope54clD5pOHZYI0SIk',
    appId: '1:958750136393:web:abe2ffe2fc0d44112b8798',
    messagingSenderId: '958750136393',
    projectId: 'ecom1-cb8a5',
    authDomain: 'ecom1-cb8a5.firebaseapp.com',
    storageBucket: 'ecom1-cb8a5.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDLqoM4sv9fiM-nUTP4wfG20pVKlnIsyTM',
    appId: '1:958750136393:android:0eecd747fb07b8272b8798',
    messagingSenderId: '958750136393',
    projectId: 'ecom1-cb8a5',
    storageBucket: 'ecom1-cb8a5.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC7qQ21VmP02DEzqtaLyIKK5_d42hc2OpU',
    appId: '1:958750136393:ios:ded1ca46c6a908cb2b8798',
    messagingSenderId: '958750136393',
    projectId: 'ecom1-cb8a5',
    storageBucket: 'ecom1-cb8a5.firebasestorage.app',
    iosBundleId: 'com.example.ecomApp1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC7qQ21VmP02DEzqtaLyIKK5_d42hc2OpU',
    appId: '1:958750136393:ios:ded1ca46c6a908cb2b8798',
    messagingSenderId: '958750136393',
    projectId: 'ecom1-cb8a5',
    storageBucket: 'ecom1-cb8a5.firebasestorage.app',
    iosBundleId: 'com.example.ecomApp1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCRLOuKuu-8Hu4Yope54clD5pOHZYI0SIk',
    appId: '1:958750136393:web:8a8f08c688e960092b8798',
    messagingSenderId: '958750136393',
    projectId: 'ecom1-cb8a5',
    authDomain: 'ecom1-cb8a5.firebaseapp.com',
    storageBucket: 'ecom1-cb8a5.firebasestorage.app',
  );
}
